### ISSUE TITLE
Publishing uniques back on npm

### ISSUE THREAD

**Issue by montanaflynn** [azer/uniques#1]
Hey @azer, I use uniques a lot in a few of my APIs and it would be nice if I could add it back to npm. I would also like to add some additional features and optimizations that might benefit the community.

**Comment by ajbogh** [comment]
@montanaflynn, if you get permission can you post the new NPM project name or link here?

For others that need an alternative, you can use underscore's uniq function:

```
npm install --save underscore
```

Edit your index.js

```
 var uniques = require('underscore').uniq;
```

**Comment by montanaflynn** [comment]
@ajbogh yes absolutely

**Comment by azer** [comment]
added

**Comment by montanaflynn** [comment]
@ajbogh I've sent npm an email and am waiting to hear back from them, will push as soon as I can.
